### PR TITLE
Extend the list of papers on package management.

### PR DESCRIPTION
**Pull request by Zimmi48**
Hi @andrew and others :wave: 

I have been collecting data on package managers, including a list of papers on package management and package ecosystems. I have added the papers from my list that were missing from this one.

But first of all, I'd like to know whether this kind of contribution is welcome.

However, it already seems like this list is too big (it was already big even before my additions), so I'd like to suggest adding some sections and sub-sections to organize it.

I was thinking first to introduce two main sections:

- Papers about package manager design

  This category could be maybe split in a sub-section on papers presenting specific package managers, and a sub-section about papers that present solutions to address specific issues, but not in the context of a specific package manager.

- Papers studying package ecosystems

  This category is interesting as well to package manager designers / maintainers, since they need to be aware of what happens in the package ecosystems, but they rarely contain suggestion on how improvement to package managers could impact the ecosystems.

  This section could be further split, maybe in sub-sections for each ecosystem studied, with a first sub-section for papers comparing several ecosystems.

Then in each sub-section, it could be useful to prominently display the year of publication, and probably sort the papers by year.

### CODE REVIEW

**Comment by andrew** [comment]
@Zimmi48 your contributions are very welcome, subsections are a great idea 👍

**Comment by Zimmi48** [comment]
OK thanks for the feedback, I'll prepare a second commit reorganizing the list then.

**Comment by Zimmi48** [comment]
Second commit pushed. This is ready for review.

**Comment by mikeal** [comment]
I know what I’m reading this weekend 🤓

**Comment by Zimmi48** [comment]
> I know what I’m reading this weekend :nerd_face:

I hope that's not the full list, otherwise you may need more than just one weekend :laughing:

**Comment by andrew** [comment]
Great work, thanks!

**Pull request merged**
